import java.util.Arrays;
import java.util.Random;

public class TEsting {


    private  static  int [][]field = new int[][] {new int[]{2}};



   /* private  static  int [][]field = new int[][]{

        new int[]{1,2,3},
                new int[]{4,5,6},
                new int[]{7,8,9},

    };*/

    public static void main(String[] args) {

      /*  for (int i = 0; i < field.length; i++ ){
            System.out.println(Arrays.toString(field[1]));

        }*/

      /*  System.out.println(Arrays.toString(field[0]));
        Random rn = new Random();


            int i = rn.nextInt(0,27);
            System.out.println(i);*/
        boolean b = false;




    }


}

/*
    void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:364053:
        if(event == GEvent.CHANGED){
            label1.setText(source.getText());
        }
    } //_CODE_:textfield1:364053:

    void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:343569:
        if(event == GEvent.CHANGED){
            label1.setText(source.getText());
        }
    } //_CODE_:textfield2:343569:

    // Create all the GUI controls.
// autogenerated do not edit
    void createGUI(){
        G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
        G4P.messagesEnabled(false);
        G4P.setCursorOff(ARROW);
        if(frame != null)
            frame.setTitle("Sketch Window");
        textfield1 = new GTextField(this, 55, 56, 160, 30, G4P.SCROLLBARS_NONE);
        textfield1.addEventHandler(this, "textfield1_change1");
        textfield2 = new GTextField(this, 57, 12, 160, 30, G4P.SCROLLBARS_NONE);
        textfield2.addEventHandler(this, "textfield2_change1");
        label1 = new GLabel(this, 57, 109, 157, 44);
        label1.setText("My label");
        label1.setOpaque(false);
    }*/

    // Variable declarations
// autogenerated do not edit
    /*GTextField textfield1;
    GTextField textfield2;
    GLabel label1;*/
